// frontend/src/views/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-background-main to-gray-200">
    <div class="max-w-md w-full space-y-8">
      <div class="card">
        <div class="card-header text-center">
          <h2 class="text-3xl font-bold text-secondary-900">
            MAU Hospital
          </h2>
          <p class="mt-2 text-sm text-secondary-600">
            Sistema de Gestión de Recetas
          </p>
        </div>

        <div class="card-body">
          <form @submit.prevent="handleSubmit" class="space-y-6">
            <div>
              <label for="username" class="form-label">
                Usuario
              </label>
              <input
                id="username"
                v-model="form.username"
                type="text"
                required
                class="form-input"
                placeholder="Ingresa tu usuario"
                :disabled="isLoading"
              />
              <p v-if="errors.username" class="form-error">
                {{ errors.username }}
              </p>
            </div>

            <div>
              <label for="password" class="form-label">
                Contraseña
              </label>
              <input
                id="password"
                v-model="form.password"
                type="password"
                required
                class="form-input"
                placeholder="Ingresa tu contraseña"
                :disabled="isLoading"
              />
              <p v-if="errors.password" class="form-error">
                {{ errors.password }}
              </p>
            </div>

            <div v-if="loginError" class="text-center">
              <p class="form-error">{{ loginError }}</p>
            </div>

            <button
              type="submit"
              :disabled="isLoading"
              class="btn-primary w-full flex items-center justify-center"
              :class="{ 'opacity-50 cursor-not-allowed': isLoading }"
            >
              <svg
                v-if="isLoading"
                class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  class="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  stroke-width="4"
                ></circle>
                <path
                  class="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                ></path>
              </svg>
              {{ isLoading ? 'Iniciando sesión...' : 'Iniciar Sesión' }}
            </button>
          </form>

          <div class="mt-6 text-center">
            <p class="text-xs text-secondary-600">
              Sistema desarrollado para MAU Hospital
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useToast } from 'vue-toastification'

export default {
  name: 'Login',
  components: {},
  setup() {
    const router = useRouter()
    const authStore = useAuthStore()
    const toast = useToast()

    const isLoading = ref(false)
    const loginError = ref('')

    const form = reactive({
      username: '',
      password: ''
    })

    const errors = reactive({
      username: '',
      password: ''
    })

    const validateForm = () => {
      errors.username = ''
      errors.password = ''

      if (!form.username.trim()) {
        errors.username = 'El usuario es requerido'
        return false
      }

      if (!form.password.trim()) {
        errors.password = 'La contraseña es requerida'
        return false
      }

      if (form.password.length < 6) {
        errors.password = 'La contraseña debe tener al menos 6 caracteres'
        return false
      }

      return true
    }

    const handleSubmit = async () => {
      if (!validateForm()) return

      try {
        isLoading.value = true
        loginError.value = ''

        const loginData = {
          username: form.username,
          password: form.password
        }

        const result = await authStore.login(loginData)

        if (result.success) {
          toast.success(`¡Bienvenido, ${result.user.first_name}!`)
          router.push('/')
        } else {
          loginError.value = result.error
        }
      } catch (error) {
        console.error('Error en login:', error)
        loginError.value = 'Error inesperado. Inténtalo de nuevo.'
      } finally {
        isLoading.value = false
      }
    }

    return {
      form,
      errors,
      isLoading,
      loginError,
      handleSubmit
    }
  }
}
</script>

// nextjs/src/app/(auth)/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

export default function LoginPage() {
  const router = useRouter()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      })

      const data = await response.json()

      if (!response.ok) {
        setError(data.error || 'Error al iniciar sesión')
      } else {
        router.push('/dashboard')
        router.refresh()
      }
    } catch (error) {
      setError('Error de conexión')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-neutral-50">
      <div className="max-w-md w-full space-y-8 p-8 bg-white rounded-lg shadow-lg">
        <div>
          <h2 className="text-center text-3xl font-bold text-neutral-900">
            MAU Hospital
          </h2>
          <p className="mt-2 text-center text-sm text-neutral-600">
            Sistema de Gestión de Recetas
          </p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div className="space-y-4">
            <div>
              <label htmlFor="username" className="block text-sm font-medium text-neutral-700">
                Usuario
              </label>
              <input
                id="username"
                name="username"
                type="text"
                autoComplete="username"
                required
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-neutral-300 rounded-md shadow-sm focus:outline-none focus:ring-neutral-500 focus:border-neutral-500"
                placeholder="admin"
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-neutral-700">
                Contraseña
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-neutral-300 rounded-md shadow-sm focus:outline-none focus:ring-neutral-500 focus:border-neutral-500"
                placeholder="••••••••"
              />
            </div>
          </div>

          {error && (
            <div className="rounded-md bg-red-50 p-4">
              <p className="text-sm text-red-800">{error}</p>
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-neutral-900 hover:bg-neutral-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-neutral-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? 'Iniciando sesión...' : 'Iniciar sesión'}
          </button>

          <div className="text-xs text-neutral-500 text-center space-y-1">
            <p>Usuarios de prueba:</p>
            <p>admin / admin123</p>
            <p>doctor1 / admin123</p>
          </div>
        </form>
      </div>
    </div>
  )
}
